[server]
enableCORS = true
enableXsrfProtection = true
headless = true
runOnSave = false
fileWatcherType = "none"
baseUrlPath = "house-frontend"



[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false